# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 22:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0039_importdlpbam'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericTaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('running', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('stopping', models.BooleanField(default=False)),
                ('state', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericTaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_script_name', models.CharField(max_length=50)),
                ('required_and_default_args', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='generictaskinstance',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tantalus.GenericTaskType'),
        ),
    ]
