# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 23:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0040_auto_20180510_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generictasktype',
            name='required_and_default_args',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'arg1': None, 'arg2': 'default2'}, help_text="The arguments that the task requires as a JSON object. Looking at the object as a dictionary, the keys are the argument names and the corresponding values are the default values for these arguments. To specify no default argument, simply use 'null' as the value.", verbose_name='script arguments'),
        ),
        migrations.AlterField(
            model_name='generictasktype',
            name='task_name',
            field=models.CharField(help_text='The name of the task.', max_length=50),
        ),
        migrations.AlterField(
            model_name='generictasktype',
            name='task_script_name',
            field=models.CharField(help_text="The name of the task script name, where the name you enter here refers to 'script_name' in the path to the script tantalus/tantalus/backend/task_scripts/{task_script_name}.py, relative to the root of the Tantalus respository.", max_length=50),
        ),
    ]
