# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 17:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import tantalus.models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0041_auto_20180511_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generictasktype',
            name='required_and_default_args',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=tantalus.generictask_models.return_gen_task_type_arg_default, help_text="The arguments that the task requires as a JSON object. Looking at the object as a dictionary, the keys are the argument names and the corresponding values are the default values for these arguments. To specify no default argument, simply use 'null' as the value.", verbose_name='script arguments'),
        ),
    ]
