# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0043_auto_20180514_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generictasktype',
            name='task_name',
            field=models.CharField(help_text=b'The name of the task.', max_length=50, unique=True),
        ),
    ]
