# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0043_auto_20180530_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='gscwgsbamquery',
            name='skip_file_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalazureblobstorage',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalserverstorage',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalstorage',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
