# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0044_auto_20180514_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='generictaskinstance',
            name='instance_name',
            field=models.CharField(default='asdljf', help_text=b'The name for the instance.', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
