# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0045_generictaskinstance_instance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generictasktype',
            name='default_host',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tantalus.ServerStorage'),
            preserve_default=False,
        ),
    ]
