# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0046_generictasktype_default_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generictasktype',
            name='default_host',
            field=models.ForeignKey(help_text=b'The default host an instance of this task will run on (unless otherwise specified)', on_delete=django.db.models.deletion.CASCADE, to='tantalus.ServerStorage'),
        ),
    ]
