# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0048_auto_20180515_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='generictaskinstance',
            name='host',
            field=models.ForeignKey(default=1, help_text=b'The host on which the task will run.', on_delete=django.db.models.deletion.CASCADE, to='tantalus.ServerStorage'),
            preserve_default=False,
        ),
    ]
