# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 16:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0049_generictaskinstance_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generictaskinstance',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text=b'The arguments to call the task type with as a JSON object. The arguments must be a subset of the arguments required by the task type.', null=True),
        ),
        migrations.AlterField(
            model_name='generictaskinstance',
            name='task_type',
            field=models.ForeignKey(help_text=b'The generic task type of which this is an instance.', on_delete=django.db.models.deletion.CASCADE, to='tantalus.GenericTaskType'),
        ),
    ]
