# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0050_auto_20180706_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractdataset',
            name='tags',
            field=models.ManyToManyField(related_name='datasets', to='tantalus.Tag'),
        ),
    ]
