# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0051_auto_20180517_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generictasktype',
            name='task_script_name',
        ),
        migrations.AddField(
            model_name='generictasktype',
            name='task_script_path',
            field=models.CharField(default=12323, help_text=b'The path of the script used by this generic task type (relative to the root of the generic task scripts directory.', max_length=400),
            preserve_default=False,
        ),
    ]
