# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tantalus', '0052_auto_20180517_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generictasktype',
            old_name='task_script_path',
            new_name='relative_script_path',
        ),
    ]
